### ISSUE TITLE
Bug: scraping

### ISSUE THREAD

**Issue by Lootmann** [Lootmann/Dict.v2#1]
```python
❯ dict own business

>>> create cache :D

Traceback (most recent call last):
  File "/home/lyota/.local/bin/dict", line 8, in <module>
    sys.exit(main())
  File "/home/lyota/.local/lib/python3.10/site-packages/dict/main.py", line 20, in main
    Cache.create_cache(input_words, scraper.construct())
  File "/home/lyota/.local/lib/python3.10/site-packages/dict/scraping.py", line 34, in construct
    "description": self.get_description(),
  File "/home/lyota/.local/lib/python3.10/site-packages/dict/scraping.py", line 57, in get_description
    return description.get_text().strip()

AttributeError: 'NoneType' object has no attribute 'get_text'
```

**Comment by Lootmann** [comment]
検索したところ 熟語は全く別のHTMLで出力されている
こんなところで使いづらい weblio

**Comment by Lootmann** [comment]
熟語、句動詞には `description` が存在していない単語がある  
そいつを検索除外するように Scraping して終了 :^)
