### ISSUE TITLE
Bug: scraping

### ISSUE THREAD

**Issue by Lootmann** [Lootmann/Dict.v2#3]
```python
❯ dict just in case

>>> create cache :D

Traceback (most recent call last):
  File "/home/lyota/.local/bin/dict", line 8, in <module>
    sys.exit(main())
  File "/home/lyota/.local/lib/python3.10/site-packages/dict/main.py", line 20, in main
    Cache.create_cache(input_words, scraper.construct())
  File "/home/lyota/.local/lib/python3.10/site-packages/dict/scraping.py", line 36, in construct
    word_info.update(self.get_part_of_speech())
  File "/home/lyota/.local/lib/python3.10/site-packages/dict/scraping.py", line 164, in get_part_of_speech
    d_part_of_speech[part_of_speech].append("".join(line))
KeyError: ''
```

**Comment by Lootmann** [comment]
これも熟語 = 句動詞のミス
品詞がないのに取得しようとしている

**Comment by Lootmann** [comment]
```python
articles = self._soup.find_all(class_="Kejje")
elements = self._soup.find_all(class_="KejjeSub")

if not articles or not elements:
     return {}
```

各品詞の親要素の `class` である, `KejjeSub` を見れば終了  
それだけ

**Comment by Lootmann** [comment]
多分治った :^)
